version: "3.8"

services:
  mail-to-telegram:
    build: .
    container_name: mail-to-telegram
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "25:25"
    volumes:
      - ./data:/app/data
    networks:
      - web_network

networks:
  web_network:
    external: true